### PR TITLE
Do not leak file descriptors

### PR DESCRIPTION
**Pull request by SvetlinZarev**
Bug: CODEC-225

### CODE REVIEW

**Comment by jochenw** [comment]
Questions on your patch:

a) In Rule.java, you are treating the Scanner as the leakable Resource. In DaitchMokotoffSoundex.java, however, its the underlying InputStream. Sounds odd to me.
b) Use of java.util.logging: Is that standard behaviour in Codec? If not, it ought to be removed.

**Comment by jochenw** [comment]
Rethinking the logger stuff: Do *not* catch the exception, or rethrow it. In general, Codec should leave the error handling to the user.

**Comment by SvetlinZarev** [comment]
> In Rule.java, you are treating the Scanner as the leakable Resource. In DaitchMokotoffSoundex.java, however, its the underlying InputStream. Sounds odd to me.

In Rule I don't have access to the underlying stream, so I close the scanner which in turn closes the stream. I can change it to close the Scanner in DaitchMokotoffSoundex as well.

>  Use of java.util.logging: Is that standard behaviour in Codec? If not, it ought to be removed.

I grepped for "log, logger, etc" and I couldn't fine any, so there is no "standard" behavior.

> Rethinking the logger stuff: Do not catch the exception, or rethrow it. In general, Codec should leave the error handling to the user.

Throwing from finally will hide the original exception, that's the reason I catch it. I also log it becaue IMO it's worse to silently drop it. An alternative approach would be to close the scanner instead of the stream. The scanner.close() does not throw exception and hence no need for logging and catching it. 

What do you think ?

Svetlin

**Comment by jochenw** [comment]
> In Rule I don't have access to the underlying stream, so I close the scanner which in turn closes the
>  stream. I can change it to close the Scanner in DaitchMokotoffSoundex as well.

Please, do.

Regarding the logging: I agree, that the original exception should not be hidden, which is why my code typically looks like this:

```
  Resource res = null;
  Throwable th = null;
  try {
    res = createResource();
    res.close();
    res = null;
  } catch (Throwable t) {
    th = t;
  } finally {
    if (res != null) {
      try {
        res.close();
      } catch (Throwable t) {
        if (th == null) { th = t; }
      }
   }
   if (th != null) {
     rethrow(t);
   }

```

Slightly more convoluted, but safe.

**Comment by SvetlinZarev** [comment]
Made the change to close() the Scanner instead of the stream.

**Comment by SvetlinZarev** [comment]
merged

**Pull request closed without merging**
